# 1. Normalization Problem

In [39]:
import numpy as np

# Create a randon 5x5 nd array
X = np.random.rand(5,5)

# Calculate the mean & standard deviation of the array
mean_X = X.mean()
std_X = X.std()

# Normalize the array using the formula: Z = (X - mean) / standard deviation 
X_normalized = (X - mean_X) / std_X

# Save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

# Print the original and normalized arrays 
print("Original array:\n", X)
print("\nNormalized array:\n", X_normalized)




Original array:
 [[0.64442862 0.31153996 0.11543769 0.12439619 0.7028066 ]
 [0.36086316 0.28309184 0.45382411 0.26004149 0.33154883]
 [0.74651928 0.35303944 0.71813637 0.70644438 0.47399934]
 [0.47648973 0.71160795 0.95072789 0.05838016 0.83935058]
 [0.76664201 0.7390947  0.90877487 0.86129906 0.16517067]]

Normalized array:
 [[ 0.45445731 -0.78676911 -1.51796649 -1.48456335  0.67212854]
 [-0.60286    -0.8928423  -0.25624085 -0.97878904 -0.71216297]
 [ 0.83511797 -0.63203195  0.72928797  0.68569259 -0.18101438]
 [-0.17172858  0.70494573  1.59654108 -1.73071424  1.18125372]
 [ 0.91014867  0.80743431  1.44011282  1.26309201 -1.33252946]]


# 2. Divisible by 3 Problem 

In [31]:
import numpy as np

# Create an array with the first 100 positive integers and square each element to create 10x10 array
integers = np.arange(1,101)**2

# Reshape to 10x10 ndarray
A = A.reshape(10,10)

# Determine the elements divisible by 3
divisible_by_3 = A[A % 3 == 0]

# Save the result to a file
np.save('div_by_3.npy', divisible_by_3)

# Print the array and the elements divisible by 3
print("10x10 Array A:\n", A)
print("\nElements divisible by 3:\n", divisible_by_3)

10x10 Array A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
